### ISSUE TITLE
Desert Pyramid dungeons empty

### ISSUE THREAD

**Issue by yggdrasil75** [fnar/minecraft-roguelike#59] opened 2021-07-13 13:15 UTC
only around 1 in 5 chests in desert dungeons contain any content, and of that, it is only 1-3 gold ingots. this makes the desert dungeons kinda worthless as anything other than a place to gather random building blocks.

**Comment by fnar** [comment] 2021-07-13 17:39
Sometimes, the process of generating a dungeon encounters an error that is so disruptive, the rest of the features of the dungeon can fail to spawn. Sometimes this is entire floors, sometimes this is rooms, sometimes it is only a few chests worth of loot.

Although this issue was in the original, I've tried very hard to *surface* it more, so that we can begin to crack down on the causes. Usually this is caused by a chest trying to generate in an 'illegal' spot, such as over a spawner.

You wouldn't happen to still have your logs from this particular dungeon generated, would you?

**Comment by fnar** [comment] 2022-02-07 09:55
Closing as this is likely a misconfiguration rather than a bug in the mod. Please feel free to re-open it if you have evidence of an issue in the mod.

**Closed by fnar** 2022-02-07 09:55 UTC
Labels: question
