### ISSUE TITLE
cascading worldgen is just killing the loading times.

### ISSUE THREAD

**Issue by ghost** [fnar/minecraft-roguelike#62] opened 2021-10-05 18:03 UTC
I know it's an issue from the original Roguelike mod, but damn is is brutal!

I think I'll have to forgo this mod, as it's the only thing holding Worldgen back. Sometimes taking minutes to unfreeze.

**Comment by fnar** [comment] 2023-10-21 21:33
Duplicate of #42

**Closed by fnar** 2023-10-21 21:33 UTC
