### ISSUE TITLE
Using 'fence' or 'minecraft:fence' for theme's staircase removes pillars entirely

### ISSUE THREAD

**Issue by srwaggon** [fnar/minecraft-roguelike#5] opened 2020-03-25 07:18 UTC

**Comment by fnar** [comment] 2021-06-18 00:01
```
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=minecraft:fence, properties=[east, north, south, west]}
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at net.minecraft.block.state.BlockStateContainer$StateImplementation.withProperty(BlockStateContainer.java:221)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at greymerk.roguelike.worldgen.MetaBlock1_2.withProperty(MetaBlock1_2.java:61)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at com.github.srwaggon.minecraft.block.BlockMapper1_12.mapStairs(BlockMapper1_12.java:625)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at greymerk.roguelike.worldgen.MetaBlock1_2.getMetaBlock(MetaBlock1_2.java:52)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at com.github.srwaggon.minecraft.WorldEditor1_12.setBlock(WorldEditor1_12.java:197)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at com.github.srwaggon.minecraft.block.SingleBlockBrush.stroke(SingleBlockBrush.java:39)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at greymerk.roguelike.worldgen.BlockBrush.stroke(BlockBrush.java:10)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at greymerk.roguelike.dungeon.rooms.prototype.CornerRoom.createCeiling(CornerRoom.java:60)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at greymerk.roguelike.dungeon.rooms.prototype.CornerRoom.generate(CornerRoom.java:31)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at greymerk.roguelike.dungeon.DungeonNode.generate(DungeonNode.java:120)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at greymerk.roguelike.dungeon.tasks.DungeonTaskRooms.generateLevel(DungeonTaskRooms.java:24)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.ArrayList.forEach(ArrayList.java:1257)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at greymerk.roguelike.dungeon.tasks.DungeonTaskRooms.execute(DungeonTaskRooms.java:17)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at greymerk.roguelike.dungeon.Dungeon.lambda$generate$1(Dungeon.java:113)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at greymerk.roguelike.dungeon.Dungeon.generate(Dungeon.java:113)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at greymerk.roguelike.command.routes.CommandRouteDungeon.generateDungeon(CommandRouteDungeon.java:89)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at greymerk.roguelike.command.routes.CommandRouteDungeon.execute(CommandRouteDungeon.java:52)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at greymerk.roguelike.command.CommandRouteBase.execute(CommandRouteBase.java:30)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at greymerk.roguelike.command.routes.CommandRouteRoguelike.execute(CommandRouteRoguelike.java:27)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at com.github.srwaggon.roguelike.command.CommandRoguelike.execute(CommandRoguelike.java:41)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:126)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at net.minecraft.command.CommandHandler.executeCommand(CommandHandler.java:98)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at net.minecraft.network.NetHandlerPlayServer.handleSlashCommand(NetHandlerPlayServer.java:1003)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at net.minecraft.network.NetHandlerPlayServer.processChatMessage(NetHandlerPlayServer.java:979)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(CPacketChatMessage.java:47)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at net.minecraft.network.play.client.CPacketChatMessage.processPacket(CPacketChatMessage.java:8)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:21)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at net.minecraft.util.Util.runTask(Util.java:53)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:798)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:192)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592)
[17:00:14] [Server thread/INFO] [STDERR]: [greymerk.roguelike.dungeon.Dungeon:generate:115]: 	at java.lang.Thread.run(Thread.java:748)
[17:00:14] [main/INFO] [minecraft/GuiNewChat]: [CHAT] �Success: Dungeon generated at {"x": 12257, "y": 0, "z": 12190}
[17:00:19] [Server thread/INFO] [minecraft/MinecraftServer]: [Player824: Set own game mode to Spectator Mode]
[17:00:20] [main/INFO] [minecraft/GuiNewChat]: [CHAT] Your game mode has been updated to Spectator Mode
[17:00:26] [Server thread/INFO] [minecraft/IntegratedServer]: Saving and pausing game...
[17:00:26] [Server thread/INFO] [minecraft/MinecraftServer]: Saving chunks for level 'New World'/overworld
```

**Comment by fnar** [comment] 2021-06-18 00:18
Decidedly not a bug. The mod currently needs to manipulate the orientation of the stairs and expects them to have stair block blockstates. Using a non-stair creates some pretty frustrating issues with no real gain. Closing for now.

**Closed by fnar** 2021-06-18 00:18 UTC
Labels: bug
