### ISSUE TITLE
Atrocious chunk generation times and issues.

### ISSUE THREAD

**Issue by DaniellSSan** [fnar/minecraft-roguelike#71] opened 2023-06-24 03:58 UTC
Love this mod but the issues it causes for chunk generation cause it to be unplayable in my experience. Generating a new world and it's chunks is relatively fast for modded minecraft but when the game tries to generate one of this mods dungeons it can take many minutes to finish a single dungeon, causing the server to have to skip thousands of ticks and causing further issues with chunk generation;
[Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 12064ms behind, skipping 241 tick(s)

Many chunks seem to error and the biome defaults to plains even though I disabled the plains biome from generating in the settings of other mods. Over 90% of my world is plains biome. Altering settings related to chunk generation have no discernable affect. This is not a cascading worldgen issue, my console does not display cascading worldgen messages.

In a few other issues on this repo it is stated that the only real fix is to have a beefy pc. How beefy exactly? Because during chunk generation my CPU never exceeds 70% usage. Or maybe I'm running another mod that is known to cause issues with roguelike dungeons?

**Comment by fnar** [comment] 2023-10-21 21:33
Duplicate of #42

**Closed by fnar** 2023-10-21 21:33 UTC
Labels: duplicate
