### ISSUE TITLE
Worldgen lag

### ISSUE THREAD

**Issue by SegoItCh** [fnar/minecraft-roguelike#76] opened 2023-10-19 10:01 UTC
[11:57:48] [Server thread/WARN] [FML]: Please report this to the mod's issue tracker.
[11:57:48] [Server thread/WARN] [FML]: Roguelike Dungeons loaded a new chunk [61, 0] in dimension 0 (overworld) while populating chunk [60, 0], causing cascading worldgen lag.

**Comment by fnar** [comment] 2023-10-21 21:32
Duplicate of #42

**Closed by fnar** 2023-10-21 21:32 UTC
Labels: duplicate
